/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2019-04-28 14:22:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1553226187728L));
    _jspx_dependants.put("jar:file:/E:/workspace/java/design/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1054243570000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!--下拉这里开始 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tvar timeout = 500;\r\n");
      out.write("\tvar closetimer = 0;\r\n");
      out.write("\tvar ddmenuitem = 0;\r\n");
      out.write("\t// open hidden layer\r\n");
      out.write("\tfunction mopen(id) {\r\n");
      out.write("\t\t// cancel close timer\r\n");
      out.write("\t\tmcancelclosetime();\r\n");
      out.write("\t\t// close old layer\r\n");
      out.write("\t\tif (ddmenuitem)\r\n");
      out.write("\t\t\tddmenuitem.style.visibility = 'hidden';\r\n");
      out.write("\t\t// get new layer and show it\r\n");
      out.write("\t\tddmenuitem = document.getElementById(id);\r\n");
      out.write("\t\tddmenuitem.style.visibility = 'visible';\r\n");
      out.write("\t}\r\n");
      out.write("\t// close showed layer\r\n");
      out.write("\tfunction mclose() {\r\n");
      out.write("\t\tif (ddmenuitem)\r\n");
      out.write("\t\t\tddmenuitem.style.visibility = 'hidden';\r\n");
      out.write("\t}\r\n");
      out.write("\t// go close timer\r\n");
      out.write("\tfunction mclosetime() {\r\n");
      out.write("\t\tclosetimer = window.setTimeout(mclose, timeout);\r\n");
      out.write("\t}\r\n");
      out.write("\t// cancel close timer\r\n");
      out.write("\tfunction mcancelclosetime() {\r\n");
      out.write("\t\tif (closetimer) {\r\n");
      out.write("\t\t\twindow.clearTimeout(closetimer);\r\n");
      out.write("\t\t\tclosetimer = null;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t// close layer when click-out\r\n");
      out.write("\tdocument.onclick = mclose;\r\n");
      out.write("// -->\r\n");
      out.write("</script>\r\n");
      out.write("<!--下拉这里结束 -->\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\tfunction Display(ID) {\r\n");
      out.write("\t\tif (ID.style.display == 'none') {\r\n");
      out.write("\t\t\tID.style.display = '';\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tID.style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!--导航FLASH -->\r\n");
      out.write("<table width=\"1004\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\tbackground=\"flash/top/nzgov_06.jpg\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\"images/top.jpg\" width=\"1004\" height=\"220\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!--导航FLASH -->\r\n");
      out.write("\r\n");
      out.write("<!--导航 -->\r\n");
      out.write("<table width=\"1004\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\tbackground=\"images/nzcms/nzcms_top01.gif\" bgcolor=\"#093887\" class=\"top\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"1004\" height=\"38\" align=\"center\" valign=\"middle\">\r\n");
      out.write("\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"sddm\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(basePath);
      out.write("\" class=\"left\"> 首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"index/doctor.action\" class=\"left\"onmouseover=\"mopen('21')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonMouseOut=\"mclosetime()\">医生信息</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"21\" onMouseOver=\"mcancelclosetime()\" onMouseOut=\"mclosetime()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"top01\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbackground=\"images/BG/01.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--导航 -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"index/bbs.action\" class=\"left\">留言板</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<!--导航 -->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!--导航-->\r\n");
      out.write("<!--滚动栏插件 -->\r\n");
      out.write("\r\n");
      out.write("<table width=\"1004\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table width=\"1004\" border=\"0\" align=\"center\" cellpadding=\"3\" cellspacing=\"0\" bgcolor=\"#000000\"\r\n");
      out.write("\t\t\t\tstyle=\"border: 5px solid #000000;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"120\" height=\"60\" align=\"center\" background=\"images/timebg.gif\" class=\"white18\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span id=localtime></span>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction showLocale(objD) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar str, colorhead, colorfoot;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar yy = objD.getYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (yy < 1900)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tyy = yy + 1900;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar MM = objD.getMonth() + 1;\r\n");
      out.write("\t\t\t\t\t\t\t\tif (MM < 10)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMM = '0' + MM;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dd = objD.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (dd < 10)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdd = '0' + dd;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar hh = objD.getHours();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (hh < 10)\r\n");
      out.write("\t\t\t\t\t\t\t\t\thh = '0' + hh;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar mm = objD.getMinutes();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (mm < 10)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmm = '0' + mm;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ss = objD.getSeconds();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ss < 10)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tss = '0' + ss;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ww = objD.getDay();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolorhead = \"<font color=\\\"#FF5300\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww > 0 && ww < 6)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolorhead = \"<font color=\\\"#FF5300\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 6)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolorhead = \"<font color=\\\"#FF5300\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期日\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期一\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 2)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期二\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 3)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期三\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 4)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期四\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 5)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期五\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ww == 6)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tww = \"星期六\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcolorfoot = \"</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstr = colorhead\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ hh\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \":\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ mm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \":\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ ss\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<br><font style='font-size: 24px':font-family: '微软雅黑';>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ ww + colorfoot;\r\n");
      out.write("\t\t\t\t\t\t\t\treturn (str);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction tick() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar today;\r\n");
      out.write("\t\t\t\t\t\t\t\ttoday = new Date();\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"localtime\").innerHTML = showLocale(today);\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.setTimeout(\"tick()\", 1000);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\ttick();\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" background=\"images/timebg.gif\">\r\n");
      out.write("\t\t\t\t\t\t<marquee scrollamount=5 width=870 onmouseover=\"stop()\" onmouseout=\"start()\">\r\n");
      out.write("\t\t\t\t\t\t\t<span style='font-family: Microsoft YaHei; color: #FFFF00; font-size: 24px;'>欢迎访问");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t</marquee>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!--滚动栏插件 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /users/header.jsp(88,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bannerList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /users/header.jsp(88,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("banner");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
            out.write("\t\t\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/article.action?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${banner.bannerid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"left\"> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${banner.bannername }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /users/header.jsp(115,10) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hosList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /users/header.jsp(115,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("hos");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=left>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100\" height=\"35\" border=\"0\" cellpadding=\"0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/hospital.action?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hos.hospitalid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><font class=\"p14\"><img src=\"images/biao.gif\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"图标\" border=\"0\">&nbsp;");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hos.hospitalname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</font> </a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /users/header.jsp(145,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t<li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"left\" onmouseover=\"mopen('20')\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tonMouseOut=\"mclosetime()\"> 用户菜单</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div id=\"20\" onMouseOver=\"mcancelclosetime()\" onMouseOut=\"mclosetime()\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"top01\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tbackground=\"images/BG/01.gif\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=left>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100\" height=\"35\" border=\"0\" cellpadding=\"0\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/prePwd.action\"><font class=\"p14\"><img src=\"images/biao.gif\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"图标\" border=\"0\">&nbsp;修改密码</font> </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=left>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100\" height=\"35\" border=\"0\" cellpadding=\"0\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/userinfo.action\"><font class=\"p14\"><img src=\"images/biao.gif\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"图标\" border=\"0\">&nbsp;个人信息</font> </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=left>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100\" height=\"35\" border=\"0\" cellpadding=\"0\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/myAsign.action\"><font class=\"p14\"><img src=\"images/biao.gif\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"图标\" border=\"0\">&nbsp;我的挂号</font> </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=left>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100\" height=\"35\" border=\"0\" cellpadding=\"0\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/electronicMD.action\"><font class=\"p14\"><img src=\"images/biao.gif\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"图标\" border=\"0\">&nbsp;电子病历</font> </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t<li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/exit.action\" class=\"left\">退出登录</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<!--导航 -->\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /users/header.jsp(226,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t<li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/preReg.action\" class=\"left\">用户注册</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<!--导航 -->\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
          out.write("\t\t\t\t\t\t\t<li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<table width=\"100\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tbackground=\"images/nzcms/nzcms.07.gif\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td height=\"38\" align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"index/preLogin.action\" class=\"left\">用户登录</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<!--导航 -->\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
